# Multivariate Gradient Descent Linear Regression - Raw Implementation

In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

In [2]:
raw_data = pd.read_csv("house_prices_grad_desc.csv")

In [3]:
raw_data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [4]:
features = ['LotFrontage', 'LotArea', 'TotalBsmtSF', 'GarageArea']
target = 'SalePrice'

In [5]:
data = raw_data[features + [target]].copy()

In [6]:
data.head()

   LotFrontage  LotArea  TotalBsmtSF  GarageArea  SalePrice
0         65.0     8450          856         548     208500
1         80.0     9600         1262         460     181500
2         68.0    11250          920         608     223500
3         60.0     9550          756         642     140000
4         84.0    14260         1145         836     250000

In [7]:
for feature in features:
    data[feature] = data[feature].fillna(data[feature].mean())

In [8]:
X = data[features].values
Y = data[target].values

In [9]:
X

array([[   65.,  8450.,   856.,   548.],
       [   80.,  9600.,  1262.,   460.],
       [   68., 11250.,   920.,   608.],
       ...,
       [   66.,  9042.,  1152.,   252.],
       [   68.,  9717.,  1078.,   240.],
       [   75.,  9937.,  1256.,   276.]], shape=(1460, 4))

In [10]:
Y

array([208500, 181500, 223500, ..., 266500, 142125, 147500], shape=(1460,))

In [11]:
# Feature scaling
X_mean = np.mean(X, axis=0)
X_std = np.std(X, axis=0)
X_std[X_std == 0] = 1e-8
X_scaled = (X - X_mean) / X_std

In [12]:
X_scaled

array([[-0.22937175, -0.20714171, -0.45930254,  0.35100032],
       [ 0.4519361 , -0.09188637,  0.46646492, -0.06073101],
       [-0.09311018,  0.07347998, -0.31336875,  0.63172623],
       ...,
       [-0.18395123, -0.14781027,  0.21564122, -1.03391416],
       [-0.09311018, -0.08016039,  0.04690528, -1.09005935],
       [ 0.22483348, -0.05811155,  0.45278362, -0.9216238 ]],
      shape=(1460, 4))

In [13]:
# Weight initialization
# w[0] = w_0, w[1] = w_1
w = np.ones(len(X[0]) + 1)

## Prediction / Hypothesis
$h_w(x) = w_0x_0 + w_1x_1 + \ldots + w_nx_n$

In [14]:
def predict(x_row, w):
    bias = w[0]
    prediction = 0.0

    for i in range(len(x_row)):
        prediction += w[i + 1] * x_row[i]

    return prediction + bias

## Cost Function
$J(w_0, w_1, \dots, w_n) = \frac{1}{2m}\sum_{i = 1}^m\{h_w(x_i) - Y_i\}^2 $

In [15]:
def cost_function(X, Y, w):
    current_cost = 0.0
    
    # number of data row
    m = len(Y)
    
    for i in range(m):
        current_cost += (predict(X[i], w) - Y[i])**2

    return current_cost / (2 * m)

## Update Function
$w_j = w_j - \alpha \frac{d}{dw_j}J(w_0, w_1, \dots, w_n)$

$w_j = w_j - \alpha \frac{1}{m}\sum_{i = 1}^m\{h_w(x_i) - Y_i\} x_{ij} $

In [16]:
def update_weights(X, Y, w, learning_rate):
    # Number of data
    m = len(Y)

    # Number of feature
    n = len(X[0])

    w_derivs = [0.0] * (n + 1)

    for i in range(m):
        error = predict(X[i], w) - Y[i] #hw(xi) - Yi

        w_derivs[0] += error 

        for j in range(n):
            w_derivs[j + 1] += error * X[i][j]

    for j in range(n+1):
        w[j] -= learning_rate * (w_derivs[j] / m)

    return w

## Main Training Loop

In [17]:
learning_rate = 0.1
epochs = 9000
tolerance = 1.0

print("Tarining Starts...")


prev_cost = cost_function(X_scaled, Y, w)

for epoch in range(1, epochs + 1):
    w = update_weights(X_scaled, Y, w, learning_rate)

    current_cost = cost_function(X_scaled, Y, w)
    
    if epoch % 50 == 0 or epoch == 1:
        print(f"Epoch {epoch}: Cost= {current_cost:,.5f}")

    cost_decrease = prev_cost - current_cost

    if tolerance > cost_decrease:
        print(f"\n[Convergence Reached] Stopped early at Epoch {epoch}!")
        print(f"The cost only decreased by {cost_decrease:.5f} (which is less than our tolerance of {tolerance})")
        print(f"Final Cost: {current_cost:,.5f}")
        break

    prev_cost = current_cost
    
print("Training Complete...")
print("-" * 50)
print(f"Final Bias (w_0)        : {w[0]:.2f}")

for j in range(len(X[0])):
    print(f"Final Weight {features[j]} : {w[j+1]:.5f}")

Tarining Starts...
Epoch 1: Cost= 15,869,422,362.54227
Epoch 50: Cost= 1,504,431,017.62006
Epoch 100: Cost= 1,503,897,956.87192

[Convergence Reached] Stopped early at Epoch 120!
The cost only decreased by 0.99526 (which is less than our tolerance of 1.0)
Final Cost: 1,503,897,853.74677
Training Complete...
--------------------------------------------------
Final Bias (w_0)        : 180920.61
Final Weight LotFrontage : 3181.16645
Final Weight LotArea : 6241.60106
Final Weight TotalBsmtSF : 30004.27890
Final Weight GarageArea : 32751.32588

In [18]:
test_data = np.array([80, 9500, 1500, 700])
test_data_scaled = (test_data - X_mean) / X_std

manual_prediction = predict(test_data_scaled, w)

print(f"Raw Model Prediction: ${manual_prediction:,.2f}")

Raw Model Prediction: $246,788.79

# Built-in Gradient Descent Linear Regression Multivariate

In [19]:
from sklearn.linear_model import SGDRegressor

In [20]:
# Initialize the built-in Gradient Descent Model
# max_iter = epochs
# eta0 = initial learning rate
sgd_model = SGDRegressor(max_iter=1000, eta0=0.1, random_state=42)

In [21]:
# Train the model using already scaled features and target!
sgd_model.fit(X_scaled, Y)

SGDRegressor(eta0=0.1, random_state=42)

In [22]:
# Scikit-Learn stores the bias in .intercept_ and the weights in .coef_
b_builtin = sgd_model.intercept_[0]
w_builtin = sgd_model.coef_

In [23]:
print("Built-in Training Complete!")
print("-" * 50)
print(f"Final Bias (w_0)        : {b_builtin:.2f}")

for j in range(len(X[0])):
    print(f"Final Weight {features[j]} : {w_builtin[j]:.2f}")

Built-in Training Complete!
--------------------------------------------------
Final Bias (w_0)        : 176494.44
Final Weight LotFrontage : 2180.66
Final Weight LotArea : 57564.75
Final Weight TotalBsmtSF : 24930.98
Final Weight GarageArea : 33785.82

In [24]:
# 1. Take the test_data_scaled you already calculated manually
test_data_scaled_2d = test_data_scaled.reshape(1, -1)

# 2. Feed it directly into the built-in model
sklearn_prediction = sgd_model.predict(test_data_scaled_2d)[0]

print(f"Scikit-Learn Prediction: ${sklearn_prediction:,.2f}")

Scikit-Learn Prediction: $232,659.25